### ISSUE TITLE
When address is '111(aaa）<bb@test.com>', parser fails

### ISSUE THREAD

**Issue by gangganghao** [nodemailer/addressparser#12]
When address is '111(aaa）<bb@test.com>', parser fails.
result : [{address:'',name:'111'}]

**Comment by andris9** [comment]
This address is malformed in so many ways, mostly because you are using the U+FF09 character `"）"` instead of `")"`. Replace the full width right parenthesis with ascii parenthesis and it should start working.

**Comment by gangganghao** [comment]
The user can customize the displayname,if the displayname contains '(）',parser fails.  
eg :    111(aaa）<bb@test.com>

**Comment by andris9** [comment]
Parens inside email addresses are comments. In your case you start a comment with the left paren `"("` but never close the comment as there is no right paren `")"`, instead you have a full width right paren `"）"` but this does not mean anything in this context, it's just another symbol, so it can't close the comment.

**Comment by gangganghao** [comment]
yes, i do not close the comment as there is no right paren ")". But,now I have received a message that contains the address, the address is parsed and an error has occurred.

**Comment by andris9** [comment]
You do not get an error from addressparser, you get an address object with an empty address part. As the input is invalidly formatted then all email clients treat this differently, there is no one "correct" way to handle parsing the address. OSX mail app for example lists "111" both as the name and the address. Gmail uses "aaa）andris@kreata.ee" as the name and "111" as address, etc.

**Comment by andris9** [comment]
Anyway, as the input is invalid, then addressparser is behaving as expected, there is no bug and there is no need to change anything. "Fixing" this would mean that some other invalid input gets handled somehow more "badly".
